---
EnableDefaultLinters: true
exclude:
  - "**/vendor/**/*"
linters:
  Rubocop:
    enabled: true
    rubocop_config:
      require: standard
      inherit_gem:
        standard: config/base.yml
      inherit_from: .erb-lint_rubocop.yml
      AllCops:
        DisabledByDefault: true
  GitHub::Accessibility::AvoidBothDisabledAndAriaDisabledCounter:
    enabled: true
  GitHub::Accessibility::AvoidGenericLinkTextCounter:
    enabled: true
  GitHub::Accessibility::DisabledAttributeCounter:
    enabled: true
  GitHub::Accessibility::IframeHasTitleCounter:
    enabled: true
  GitHub::Accessibility::ImageHasAltCounter:
    enabled: true
  GitHub::Accessibility::LandmarkHasLabelCounter:
    enabled: true
  GitHub::Accessibility::LinkHasHrefCounter:
    enabled: true
  GitHub::Accessibility::NestedInteractiveElementsCounter:
    enabled: true
  GitHub::Accessibility::NoAriaLabelMisuseCounter:
    enabled: true
  GitHub::Accessibility::NoPositiveTabIndexCounter:
    enabled: true
  GitHub::Accessibility::NoRedundantImageAltCounter:
    enabled: true
  GitHub::Accessibility::NoTitleAttributeCounter:
    enabled: true
  GitHub::Accessibility::SvgHasAccessibleTextCounter:
    enabled: true
