---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/occupation-standards":
    get:
      summary: List occupation standards
      responses:
        '200':
          description: successful
          content:
            application/vnd.api+json:
              example:
                data:
                - id: 90c80480-1873-4fc0-a3c2-c9b1e477fe49
                  type: occupation_standards
                  links:
                    self: http://www.example.com/api/v1/occupation-standards/90c80480-1873-4fc0-a3c2-c9b1e477fe49
                  attributes:
                    title: Automotive Technician Specialist
                    existing_title:
                    sponsor_name:
                    registration_agency: California (SAA)
                    onet_code: 49-3023.02
                    rapids_code: '1034'
                    occupation_type: competency_based
                    term_months: 24
                    probationary_period_months: 12
                    apprenticeship_to_journeyworker_ratio: '1:1'
                    ojt_hours_min: 1000
                    ojt_hours_max: 1500
                    rsi_hours_min: 200
                    rsi_hours_max: 250
                - id: 438b1f0a-935c-4416-acb2-6ae1851ff33a
                  type: occupation_standards
                  links:
                    self: http://www.example.com/api/v1/occupation-standards/438b1f0a-935c-4416-acb2-6ae1851ff33a
                  attributes:
                    title: Human Resource Specialist
                    existing_title: Career Development Technician
                    sponsor_name: HR Industries, Inc
                    registration_agency: California (SAA)
                    onet_code: 51-7011.00
                    rapids_code: '0857'
                    occupation_type: time_based
                    term_months: 12
                    probationary_period_months: 6
                    apprenticeship_to_journeyworker_ratio: '5:1'
                    ojt_hours_min: 100
                    ojt_hours_max: 150
                    rsi_hours_min: 300
                    rsi_hours_max: 350
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        type:
                          type: string
                        links:
                          type: object
                          properties:
                            self:
                              type: string
                          required:
                          - self
                        attributes:
                          type: object
                          properties:
                            title:
                              type: string
                            existing_title:
                              type: string
                              nullable: true
                            sponsor_name:
                              type: string
                              nullable: true
                            registration_agency:
                              type: string
                            onet_code:
                              type: string
                              nullable: true
                            rapids_code:
                              type: string
                              nullable: true
                            occupation_type:
                              type: string
                            term_months:
                              type: integer
                              nullable: true
                            probationary_period_months:
                              type: integer
                              nullable: true
                            apprenticeship_to_journeyworker_ratio:
                              type: string
                              nullable: true
                            ojt_hours_min:
                              type: integer
                              nullable: true
                              description: Minimum on the job hours required
                            ojt_hours_max:
                              type: integer
                              nullable: true
                              description: Maximum on the job hours required
                            rsi_hours_min:
                              type: integer
                              nullable: true
                              description: Minimum related instruction hours required
                            rsi_hours_max:
                              type: integer
                              nullable: true
                              description: Maximum related instruction hours required
                          required:
                          - title
                          - registration_agency
                      required:
                      - id
                      - type
                      - attributes
                      - links
                required:
                - data
  "/api/v1/occupation-standards/{id}":
    get:
      summary: Retrieve occupation standard
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
          content:
            application/vnd.api+json:
              example:
                data:
                  id: 7ddc906c-9bbc-4e03-a7cd-6d62ee3eb6a2
                  type: occupation_standards
                  links:
                    self: http://www.example.com/api/v1/occupation-standards/7ddc906c-9bbc-4e03-a7cd-6d62ee3eb6a2
                  attributes:
                    title: Human Resource Specialist
                    existing_title: Career Development Technician
                    sponsor_name: HR Industries, Inc
                    registration_agency: California (SAA)
                    onet_code: 51-7011.00
                    rapids_code: '0857'
                    occupation_type: time_based
                    term_months: 12
                    probationary_period_months: 6
                    apprenticeship_to_journeyworker_ratio: '5:1'
                    ojt_hours_min: 100
                    ojt_hours_max: 150
                    rsi_hours_min: 300
                    rsi_hours_max: 350
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      type:
                        type: string
                      links:
                        type: object
                        properties:
                          self:
                            type: string
                        required:
                        - self
                      attributes:
                        type: object
                        properties:
                          title:
                            type: string
                          existing_title:
                            type: string
                            nullable: true
                          sponsor_name:
                            type: string
                            nullable: true
                          registration_agency:
                            type: string
                          onet_code:
                            type: string
                            nullable: true
                          rapids_code:
                            type: string
                            nullable: true
                          occupation_type:
                            type: string
                          term_months:
                            type: integer
                            nullable: true
                          probationary_period_months:
                            type: integer
                            nullable: true
                          apprenticeship_to_journeyworker_ratio:
                            type: string
                            nullable: true
                          ojt_hours_min:
                            type: integer
                            nullable: true
                            description: Minimum on the job hours required
                          ojt_hours_max:
                            type: integer
                            nullable: true
                            description: Maximum on the job hours required
                          rsi_hours_min:
                            type: integer
                            nullable: true
                            description: Minimum related instruction hours required
                          rsi_hours_max:
                            type: integer
                            nullable: true
                            description: Maximum related instruction hours required
                        required:
                        - title
                        - registration_agency
                    required:
                    - id
                    - type
                    - attributes
                    - links
                required:
                - data
  "/api/v1/occupations":
    get:
      summary: List occupations
      responses:
        '200':
          description: successful
          content:
            application/vnd.api+json:
              example:
                data:
                - id: aa966d77-3b13-44e6-a436-a73e533c53a8
                  type: occupations
                  links:
                    self: http://www.example.com/api/v1/occupations/aa966d77-3b13-44e6-a436-a73e533c53a8
                  attributes:
                    name: Accordion Maker
                    onet_code:
                    rapids_code: '0860'
                    time_based_hours: 8000
                    competency_based_hours: 8500
                - id: bb4fe85d-0334-4858-a58d-bcc4f416b8c9
                  type: occupations
                  links:
                    self: http://www.example.com/api/v1/occupations/bb4fe85d-0334-4858-a58d-bcc4f416b8c9
                  attributes:
                    name: Information Technology Specialist
                    onet_code: 51-7011.00
                    rapids_code: '1132'
                    time_based_hours: 2782
                    competency_based_hours: 2000
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        type:
                          type: string
                        links:
                          type: object
                          properties:
                            self:
                              type: string
                          required:
                          - self
                        attributes:
                          type: object
                          properties:
                            name:
                              type: string
                            onet_code:
                              type: string
                              nullable: true
                            rapids_code:
                              type: string
                              nullable: true
                            time_based_hours:
                              type: integer
                              nullable: true
                            competency_based_hours:
                              type: integer
                              nullable: true
                          required:
                          - name
                      required:
                      - id
                      - type
                      - attributes
                      - links
                required:
                - data
  "/api/v1/occupations/{id}":
    get:
      summary: Retrieve occupation
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
          content:
            application/vnd.api+json:
              example:
                data:
                  id: 8ce51c2c-336a-4b2c-8ca6-24c58602a7c0
                  type: occupations
                  links:
                    self: http://www.example.com/api/v1/occupations/8ce51c2c-336a-4b2c-8ca6-24c58602a7c0
                  attributes:
                    name: Information Technology Specialist
                    onet_code: 51-7011.00
                    rapids_code: '1132'
                    time_based_hours: 2782
                    competency_based_hours: 2000
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      type:
                        type: string
                      links:
                        type: object
                        properties:
                          self:
                            type: string
                        required:
                        - self
                      attributes:
                        type: object
                        properties:
                          name:
                            type: string
                          onet_code:
                            type: string
                            nullable: true
                          rapids_code:
                            type: string
                            nullable: true
                          time_based_hours:
                            type: integer
                            nullable: true
                          competency_based_hours:
                            type: integer
                            nullable: true
                        required:
                        - name
                      required:
                      - id
                      - type
                      - attributes
                      - links
                required:
                - data
servers:
- url: https://admin.apprenticeshipstandards.org
  description: Production server
- url: http://localhost:3000
  description: Local development server (uses test data)
- url: http://admin.example.localhost:3000
  description: Local development server (uses test data)
