---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/occupations":
    get:
      summary: List occupations
      responses:
        '200':
          description: successful
          content:
            application/vnd.api+json:
              example:
                data:
                - id: 89e62581-322e-4164-be19-c3f492781327
                  type: occupations
                  links:
                    self: http://www.example.com/api/v1/occupations/89e62581-322e-4164-be19-c3f492781327
                  attributes:
                    name: Accordion Maker
                    onet_code:
                    rapids_code: '0860'
                    time_based_hours: 8000
                    competency_based_hours: 8500
                - id: 490079a7-f465-40d1-a6b5-6afc3d8980ef
                  type: occupations
                  links:
                    self: http://www.example.com/api/v1/occupations/490079a7-f465-40d1-a6b5-6afc3d8980ef
                  attributes:
                    name: Information Technology Specialist
                    onet_code: 51-7011.00
                    rapids_code: '1132'
                    time_based_hours: 2782
                    competency_based_hours: 2000
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        type:
                          type: string
                        attributes:
                          type: object
                          properties:
                            name:
                              type: string
                            onet_code:
                              type: string
                              nullable: true
                            rapids_code:
                              type: string
                              nullable: true
                            time_based_hours:
                              type: integer
                              nullable: true
                            competency_based_hours:
                              type: integer
                              nullable: true
                          required:
                          - name
                      required:
                      - id
                      - type
                      - attributes
                required:
                - data
servers:
- url: http://localhost:3000
  description: Local development server (uses test data)
- url: http://admin.example.localhost:3000
  description: Local development server (uses test data)
