name: Deploy
permissions:
  contents: read

on:
  push:
    branches:
      - main

concurrency:
  group: deploy-main
  cancel-in-progress: false

jobs:
  deploy_staging:
    name: Deploy staging
    uses: ./.github/workflows/deploy_heroku_app.yml
    with:
      heroku_app: apprenticeship-standards-stag
      environment: staging
      environment_label: Staging
    secrets: inherit

  deploy_production:
    name: Deploy production
    needs: deploy_staging
    uses: ./.github/workflows/deploy_heroku_app.yml
    with:
      heroku_app: apprenticeship-standards-dot-o
      environment: production
      environment_label: Production
    secrets: inherit
