name: RSpec
permissions:
  contents: read
  pull-requests: write

on:
  push:
    paths-ignore:
      - "bin/*"
      - "**.md"
    branches:
      - "**-wip"
      - "main"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "bin/*"
      - "**.md"

jobs:
  rspec:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: app_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.10.3
        ports:
          - 9200:9200
          - 9300:9300
        env:
          discovery.type: single-node
          xpack.security.enabled: false
        options: >-
            --health-cmd "curl -f -X GET localhost:9200/_cluster/health?wait_for_status=green&timeout=1s || exit 1"
            --health-interval 5s
            --health-timeout 2s
            --health-retries 12
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "23.6.1"

      - name: Set up Ruby
        uses: ruby/setup-ruby@1287d2b408066abada82d5ad1c63652e758428d9
        with:
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Install js dependencies
        run: yarn install

      - name: Run tests
        env:
          RAILS_ENV: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB_TEST: app_test
          CI: true
          ELASTICSEARCH_URL: http://localhost:9200
        run: |
          bundle exec rails db:schema:load
          bundle exec rails after_party:generate_synonym_set
          bundle exec rake assets:precompile
          bundle exec rspec spec

      - name: Archive selenium screenshots
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: selenium-screenshots
          path: ${{ github.workspace }}/tmp/capybara/*.png
          overwrite: true
